version: '2'
services:

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana

  postgres:
    container_name: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    image: "postgres"

  pgadmin:
    container_name: pgadmin4
    ports:
      - "54888:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres
      PGADMIN_DEFAULT_PASSWORD: postgres
#      PGADMIN_LISTEN_PORT: 54888
    image: "dpage/pgadmin4"

volumes:
   postgres-data:
   pgadmin-data:
   grafana-data:
